-- Mark return-charge rows created by the vehicle-return overage detection, so
-- that flow can replace its own rows on a re-return without touching lines an
-- operator added by hand. Additive: one NOT NULL column with a default.

ALTER TABLE "ContractReturnCharge" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
