-- Tag each return-charge line with the flow that owns it, so an auto-sync
-- (return-modal km/fuel, HGS toll check) can replace only its own rows without
-- touching lines an operator added by hand.
--   MANUAL  - added on the Dönüş Ekstra tab
--   RETURN  - km-overage / missing-fuel, posted by "Araç Teslim Al"
--   HGS     - HGS/OGS toll debt, mirrored from the contract's HGS check block
-- Additive: one NOT NULL column with a default; existing auto rows become RETURN.

ALTER TABLE "ContractReturnCharge" ADD COLUMN "source" TEXT NOT NULL DEFAULT 'MANUAL';

UPDATE "ContractReturnCharge" SET "source" = 'RETURN' WHERE "autoGenerated" = true;
